import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
	title: "Sign In Owner",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html suppressHydrationWarning>
			<body>{children}</body>
		</html>
	);
}
